import { Plan } from '../../../plan.model';

export const volunteering: Plan[] = [
    {
      id: '1',
      image: 'assets/images/wildlife-rescue-team.jpg',
      title: 'Nature Trust Turtle Rescue',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '2',
      image: 'assets/images/wwf.jpg',
      title: 'WWF',
      location: 'Malta',
      type: 'ong1',
    },
    {
      id: '3',
      image: 'assets/images/greenpeace.png',
      title: 'Greenpeace',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '4',
      image: 'assets/images/grf.jpg',
      title: 'Genista Research Foundation',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '5',
      image: 'assets/images/ntm.png',
      title: 'Nature Trust Malta',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '6',
      image: 'assets/images/foe.png',
      title: 'Friends of the Earth',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '7',
      image: 'assets/images/faa.png',
      title: 'Flimkien Ghal Ambjent Ahjar',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '8',
      image: 'assets/images/breedsOrigin.jpg',
      title: 'Breeds of Origin Conservancy',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '9',
      image: 'assets/images/errc.png',
      title: 'Emergency Response and Rescue Corps',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '10',
      image: 'assets/images/majjistral.png',
      title: 'Heritage Parks Federation',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '11',
      image: 'assets/images/greenhouse.png',
      title: 'Greenhouse Malta',
      location: 'Malta',
      type: 'ong2',
    },
    {
      id: '12',
      image: 'assets/images/youthAssociation.png',
      title: 'Malta UNESCO Youth Association',
      location: 'Malta',
      type: 'ong2',
    },
  ];